require('dotenv').config()

const DEBUG = process.env.DEBUG
const LOCAL_SERVER_URL = process.env.LOCAL_SERVER_URL
const PRODUCTION_SERVER_URL = process.env.PRODUCTION_SERVER_URL
const LOCAL_MONGODB_CONNECTION_STRING = process.env.LOCAL_MONGODB_CONNECTION_STRING
const PRODUCTION_MONGODB_CONNECTION_STRING = process.env.PRODUCTION_MONGODB_CONNECTION_STRING
const COOKIE_SECRET = process.env.COOKIE_SECRET
const PORT = process.env.PORT

module.exports = {
    DEBUG: DEBUG,
    SERVER_URL: DEBUG === 'false' ? PRODUCTION_SERVER_URL : LOCAL_SERVER_URL,
    MONGODB_CONNECTION_STRING: DEBUG === 'false' ? PRODUCTION_MONGODB_CONNECTION_STRING : LOCAL_MONGODB_CONNECTION_STRING,
    COOKIE_SECRET: COOKIE_SECRET,
    PORT: PORT,
    SHEET_ID: process.env.SHEET_ID
}
